# Generated by Django 5.1.6 on 2025-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodywork', models.CharField(max_length=90)),
                ('engine', models.CharField(max_length=90)),
                ('transmission', models.CharField(max_length=90)),
                ('rudder', models.CharField(max_length=90)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=90)),
                ('volume', models.IntegerField()),
                ('condition', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
