# Generated by Django 5.1.6 on 2025-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0002_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='bodywork',
            field=models.CharField(max_length=90, verbose_name='кузов'),
        ),
        migrations.AlterField(
            model_name='description',
            name='color',
            field=models.CharField(max_length=90, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='description',
            name='condition',
            field=models.CharField(max_length=90, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=250, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='engine',
            field=models.CharField(max_length=90, verbose_name='двигатель'),
        ),
        migrations.AlterField(
            model_name='description',
            name='rudder',
            field=models.CharField(max_length=90, verbose_name='руль'),
        ),
        migrations.AlterField(
            model_name='description',
            name='transmission',
            field=models.CharField(max_length=90, verbose_name='коробка передач'),
        ),
    ]
