# Generated by Django 5.1.6 on 2025-02-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0003_alter_description_bodywork_alter_description_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterModelOptions(
            name='desktop',
            options={'verbose_name': 'Главный', 'verbose_name_plural': 'Главный'},
        ),
        migrations.AlterField(
            model_name='description',
            name='bodywork',
            field=models.CharField(max_length=90, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='description',
            name='color',
            field=models.CharField(max_length=90, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='description',
            name='condition',
            field=models.CharField(max_length=90, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='description',
            name='engine',
            field=models.CharField(max_length=90, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='description',
            name='mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='description',
            name='rudder',
            field=models.CharField(max_length=90, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='description',
            name='transmission',
            field=models.CharField(max_length=90, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='description',
            name='volume',
            field=models.IntegerField(verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='brand',
            field=models.CharField(max_length=90, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='image',
            field=models.ImageField(upload_to='cars/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='model',
            field=models.CharField(max_length=90, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chief.photo', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
