# Generated by Django 5.1.6 on 2025-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0004_photo_alter_description_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=90, verbose_name='Характеристика')),
                ('brand', models.CharField(max_length=90, verbose_name='Бренд')),
                ('model', models.CharField(max_length=90, verbose_name='Марка')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=90, verbose_name='Бренд')),
                ('model', models.CharField(max_length=90, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Изображение')),
            ],
        ),
    ]
