# Generated by Django 5.1.6 on 2025-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0006_brand_alter_favorites_options_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=90, verbose_name='Бренд')),
                ('model', models.CharField(max_length=90, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Все машины',
                'verbose_name_plural': 'Все машины',
            },
        ),
    ]
