# Generated by Django 5.1.6 on 2025-02-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0008_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='chief.brand'),
            preserve_default=False,
        ),
    ]
