# Generated by Django 5.1.6 on 2025-02-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0009_filters_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filterss', to='chief.brand'),
        ),
    ]
